# Generated by Django 5.2.4 on 2025-07-19 06:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aseguradora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la Aseguradora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aseguradora",
                "verbose_name_plural": "Aseguradoras",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nombre del Cliente"
                    ),
                ),
                (
                    "nit",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="NIT",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoOperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tipo de Operación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Operación",
                "verbose_name_plural": "Tipos de Operación",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_solicitud_cliente",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha Solicitud Cliente",
                    ),
                ),
                (
                    "fecha_envio_cliente",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Envío Cliente"
                    ),
                ),
                (
                    "ramo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ramo"
                    ),
                ),
                (
                    "numero_poliza",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número Póliza",
                    ),
                ),
                (
                    "grupo_empresarial",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Grupo Empresarial",
                    ),
                ),
                (
                    "numero_radicado_cia",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número Radicado Cía",
                    ),
                ),
                (
                    "numero_aus_ticket",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número AUS Ticket",
                    ),
                ),
                (
                    "solicitado_por",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Solicitado Por",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En Proceso", "En Proceso"),
                            ("Completado", "Completado"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "aseguradora",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tareas.aseguradora",
                        verbose_name="Aseguradora",
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas_asignadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propietario",
                    ),
                ),
                (
                    "tomador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tareas.cliente",
                        verbose_name="Tomador",
                    ),
                ),
                (
                    "tipo_operacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tareas.tipooperacion",
                        verbose_name="Tipo de Operación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "ordering": ["-fecha_solicitud_cliente"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudAsunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asunto_texto",
                    models.TextField(verbose_name="Asunto/Detalle de Solicitud"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_asunto",
                        to="tareas.tarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Asunto",
                "verbose_name_plural": "Solicitudes de Asunto",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="NotaGestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota_texto", models.TextField(verbose_name="Nota de Gestión")),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario de Creación",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_gestion",
                        to="tareas.tarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Gestión",
                "verbose_name_plural": "Notas de Gestión",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
