# Generated by Django 5.2.4 on 2025-07-19 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tareas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ramo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Ramo",
                "verbose_name_plural": "Ramos",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="notagestion",
            options={
                "ordering": ["fecha_registro"],
                "verbose_name": "Nota de Gestión",
                "verbose_name_plural": "Notas de Gestión",
            },
        ),
        migrations.AlterModelOptions(
            name="solicitudasunto",
            options={
                "ordering": ["fecha_registro"],
                "verbose_name": "Solicitud/Asunto",
                "verbose_name_plural": "Solicitudes/Asuntos",
            },
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="nit",
        ),
        migrations.AlterField(
            model_name="aseguradora",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="notagestion",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Registro"
            ),
        ),
        migrations.AlterField(
            model_name="notagestion",
            name="nota_texto",
            field=models.TextField(verbose_name="Texto de la Nota"),
        ),
        migrations.AlterField(
            model_name="notagestion",
            name="usuario_creacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudasunto",
            name="asunto_texto",
            field=models.TextField(verbose_name="Descripción del Asunto"),
        ),
        migrations.AlterField(
            model_name="solicitudasunto",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Registro"
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("En Proceso", "En Proceso"),
                    ("Completada", "Completada"),
                    ("Anulada", "Anulada"),
                ],
                default="Pendiente",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Actualización"
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="fecha_envio_cliente",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Envío (Cliente)"
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="fecha_solicitud_cliente",
            field=models.DateField(verbose_name="Fecha de Solicitud (Cliente)"),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="numero_poliza",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Número de Póliza"
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="numero_radicado_cia",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Número Radicado Compañía",
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="propietario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Propietario Asignado",
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="solicitado_por",
            field=models.CharField(
                default="", max_length=100, verbose_name="Solicitado Por"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tarea",
            name="tomador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tareas.cliente",
                verbose_name="Tomador (Cliente)",
            ),
        ),
        migrations.AlterField(
            model_name="tipooperacion",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="ramo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tareas.ramo",
                verbose_name="Ramo",
            ),
        ),
    ]
