# Generated by Django 5.2.4 on 2025-07-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tareas", "0004_solicitudasunto_usuario_creacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="eliminado_logicamente",
            field=models.BooleanField(
                default=False, verbose_name="Eliminado Lógicamente"
            ),
        ),
    ]
