# Generated by Django 5.2.4 on 2025-07-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tareas", "0005_tarea_eliminado_logicamente"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarea",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
            },
        ),
        migrations.AddField(
            model_name="tarea",
            name="asunto",
            field=models.TextField(
                default="Sin Asunto", verbose_name="Asunto/Descripción Principal"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tarea",
            name="descripcion",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción Adicional"
            ),
        ),
        migrations.AddField(
            model_name="tarea",
            name="titulo",
            field=models.CharField(
                default="Sin Asunto", max_length=200, verbose_name="Título de la Tarea"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="SolicitudAsunto",
        ),
    ]
