# Generated by Django 5.2.4 on 2025-07-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tareas", "0006_alter_tarea_options_tarea_asunto_tarea_descripcion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarea",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="tarea",
            name="titulo",
        ),
    ]
